# This file is part of the Arcadia project.
#version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    # En dev, on monte le code hors vendor pour hot-reload,
    # tout en préservant vendor dans un volume Docker
    volumes:
      - .:/var/www/html:delegated
      - vendor_data:/var/www/html/vendor
    depends_on:
      - db
      # - mongo   # décommentez si vous voulez attendre le mongo local
    environment:
      # MongoDB Atlas
      MONGODB_URI: "mongodb+srv://moerkerkeaxelprog:LR9sowBG1Hc2g0uH@cluster0.zx9bdsi.mongodb.net/arcadia?retryWrites=true&w=majority"
      # MySQL
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: arcadia
      DB_USERNAME: arcadia-user
      DB_PASSWORD: azerty123

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arcadia
      MYSQL_USER: arcadia-user
      MYSQL_PASSWORD: azerty123
    ports:
      - "3307:3306"
    volumes:
      - ./arcadia_dump.sql:/docker-entrypoint-initdb.d/arcadia_dump.sql

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    # Ne sert qu’en dev pour importer votre dump local
    #volumes:#
     # - ./mongo-dump/arcadia:/docker-entrypoint-initdb.d/arcadia

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  vendor_data: