app = "arcadia-backend"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  MONGODB_URI = "mongodb+srv://moerkerkeaxelprog:LR9sowBG1Hc2g0uH@cluster0.zx9bdsi.mongodb.net/arcadia?retryWrites=true&w=majority"
  DB_HOST = "localhost"   # ou une valeur bidon si inutilisé sur Fly
  DB_PORT = "3306"
  DB_DATABASE = "arcadia"
  DB_USERNAME = "arcadia-user"
  DB_PASSWORD = "azerty123"

[[services]]
  internal_port = 8080      # correspond à ton Apache modifié
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443