# fly.toml app configuration file generated for arcadia-backend on 2025-05-15T18:02:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arcadia-backend'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_DATABASE = 'arcadia'
  DB_HOST = 'localhost'
  DB_PASSWORD = 'azerty123'
  DB_PORT = '3306'
  DB_USERNAME = 'arcadia-user'
  MONGODB_URI="mongodb+srv://moerkerkeaxelprog:jB2xdVOzackAC3Im@cluster0.zx9bdsi.mongodb.net/arcadia?retryWrites=true&w=majority"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'
